[git]
private-commits = "description(glob:'private:*')"
sign-on-push = true

[signing]
behavior = "drop"
backend = "ssh"
key = "~/.ssh/id_personal.pub"

[ui]
default-command = ["log"]

[user]
email = "4723788+augustomelo@users.noreply.github.com"
name = "Augusto Melo"

[[--scope]]
--when.commands = ["log", "status"]
[--scope.ui]
paginate = "never"

[[--scope]]
--when.commands = ["diff", "show"]
[--scope.ui]
diff-formatter = ":git"
pager = "delta"
